"""Type stubs for the whiskeysour Rust extension module."""

from typing import Any, Dict, Iterator, List, Optional

class _Tag:
    # Identity
    @property
    def name(self) -> Optional[str]: ...
    @property
    def attrs(self) -> Dict[str, Any]: ...
    def get(self, key: str) -> Optional[Any]: ...
    def has_attr(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...

    # String content
    @property
    def string(self) -> Optional[str]: ...
    @string.setter
    def string(self, value: str) -> None: ...
    @property
    def strings(self) -> List[str]: ...
    @property
    def stripped_strings(self) -> List[str]: ...
    def get_text(self, separator: str = "", strip: bool = False) -> str: ...

    # Tree navigation
    @property
    def parent(self) -> Optional["_Tag"]: ...
    @property
    def parents(self) -> List["_Tag"]: ...
    @property
    def contents(self) -> List[Any]: ...
    @property
    def children(self) -> List[Any]: ...
    @property
    def descendants(self) -> List[Any]: ...
    @property
    def next_sibling(self) -> Optional[Any]: ...
    @property
    def previous_sibling(self) -> Optional[Any]: ...
    @property
    def next_siblings(self) -> List[Any]: ...
    @property
    def previous_siblings(self) -> List[Any]: ...
    @property
    def next_element(self) -> Optional[Any]: ...
    @property
    def previous_element(self) -> Optional[Any]: ...

    # Find / select
    def find_all(
        self,
        name: Any = None,
        attrs: Dict[str, Any] = {},
        recursive: bool = True,
        string: Any = None,
        limit: int = 0,
    ) -> List["_Tag"]: ...
    def select(self, selector: str, limit: int = 0) -> List["_Tag"]: ...
    def select_one(self, selector: str) -> Optional["_Tag"]: ...

    # Traversal
    def find_next(self, name: Any = None, attrs: Dict[str, Any] = {}, string: Any = None) -> Optional["_Tag"]: ...
    def find_next_sibling(self, name: Any = None, attrs: Dict[str, Any] = {}, string: Any = None) -> Optional["_Tag"]: ...
    def find_next_siblings(self, name: Any = None, attrs: Dict[str, Any] = {}, string: Any = None, limit: int = 0) -> List["_Tag"]: ...
    def find_previous_sibling(self, name: Any = None, attrs: Dict[str, Any] = {}, string: Any = None) -> Optional["_Tag"]: ...
    def find_previous_siblings(self, name: Any = None, attrs: Dict[str, Any] = {}, string: Any = None, limit: int = 0) -> List["_Tag"]: ...
    def find_parent(self, name: Any = None, attrs: Dict[str, Any] = {}) -> Optional["_Tag"]: ...
    def find_parents(self, name: Any = None, attrs: Dict[str, Any] = {}, limit: int = 0) -> List["_Tag"]: ...

    # Mutation
    def decompose(self) -> None: ...
    def extract(self) -> None: ...
    def replace_with(self, other: "_Tag") -> None: ...
    def insert(self, position: int, other: "_Tag") -> None: ...
    def append(self, other: "_Tag") -> None: ...
    def prepend(self, other: "_Tag") -> None: ...
    def insert_before(self, other: "_Tag") -> None: ...
    def insert_after(self, other: "_Tag") -> None: ...
    def clear(self) -> None: ...
    def wrap(self, other: "_Tag") -> None: ...
    def unwrap(self) -> None: ...

    # Serialisation
    def __str__(self) -> str: ...
    def prettify(self, indent_width: int = 2) -> str: ...
    def decode(self, indent_level: int = 0) -> str: ...
    def decode_contents(self, indent_level: int = 0) -> str: ...
    def encode(self, encoding: str = "utf-8") -> bytes: ...
    def encode_contents(self, encoding: str = "utf-8") -> bytes: ...

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class _Document:
    def __init__(self, markup: str, features: str, from_encoding: str) -> None: ...

    # Document elements
    @property
    def html(self) -> Optional[_Tag]: ...
    @property
    def head(self) -> Optional[_Tag]: ...
    @property
    def body(self) -> Optional[_Tag]: ...
    @property
    def title(self) -> Optional[_Tag]: ...
    @property
    def contents(self) -> List[Any]: ...
    def get_text(self, separator: str = "", strip: bool = False) -> str: ...

    # Factory
    def new_tag(self, name: str, attrs: Dict[str, str]) -> _Tag: ...

    # Find / select
    def find_all(
        self,
        name: Any = None,
        attrs: Dict[str, Any] = {},
        recursive: bool = True,
        string: Any = None,
        limit: int = 0,
    ) -> List[_Tag]: ...
    def select(self, selector: str, limit: int = 0) -> List[_Tag]: ...
    def select_one(self, selector: str) -> Optional[_Tag]: ...

    # Dynamic attribute access (soup.div, soup.p, etc.)
    def __getattr__(self, name: str) -> Optional[_Tag]: ...

    # Serialisation
    def __str__(self) -> str: ...
    def prettify(self, indent_width: int = 2) -> str: ...
    def encode(self, encoding: str = "utf-8") -> bytes: ...
    def decode(self, indent_level: int = 0) -> str: ...
